In [70]:
import pandas as pd

In [71]:
import numpy as np

In [72]:
from sklearn.linear_model import LinearRegression

##### 1. Напишіть функцію гіпотези лінійної регресії у векторному вигляді;

# $$
h(\vec x)= w_0 + \vec w_1 x
$$

In [73]:
def h(w_0, w_1, x):
    return w_0 + w_1 * x

##### 2. Cтворіть функцію для обчислення функції втрат у векторному вигляді

# $$
J(W) = \frac {1}{2m} \sum (h(\vec x) - \vec y)^2
$$

In [74]:
def j(data, w_0, w_1, m):
    cost = 0 

    for x, y in zip(df.x, df.y):

        cost = cost + (h(w_0, w_1, x) - y)**2

    return cost/(2*m)

##### 3. Реалізуйте один крок градієнтного спуску

# $$
w_0 = w^{prev}_0 - \alpha \frac {\partial J(w_0, w_1)}{\partial w_0}
$$
# $$
w_1 = w^{prev}_1 - \alpha \frac {\partial J(w_0, w_1)}{\partial w_1}
$$

In [75]:
def w_0(w_0_prev, learn_rate, J, w_0):
    return w_0_prev - learn_rate*(j / w_0)

In [76]:
def w_1(w_1_prev, learn_rate, J, w_1):
    return w_1_prev - learn_rate*(j / w_1)

##### 4. Знайдіть найкращі параметри w⃗ для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень

In [77]:
url = 'https://drive.google.com/file/d/1-rAa4XT4_fI0dOBlMNuE6a7jB0wln_Qo/view'
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
data = pd.read_csv(url)
data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement   
0    13300000  7420         4          2        3      yes        no       no  \
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [78]:
science_data = data.iloc[:, 0:4]
x = science_data[['area', 'bedrooms', 'bathrooms']]

y = science_data['price']

reg = LinearRegression().fit(x, y)
reg.score(x, y)

0.4870830667058762

In [79]:
reg.intercept_

-173171.6076326333

In [80]:
reg.coef_

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

##### 5. Знайдіть ці ж параметри за допомогою аналітичного рішення


# $$
h(\vec x) = \vec w * \vec x
$$

# $$
\nabla J(\vec w) = \frac {1}{m} X^T (X \vec w - \vec y)
$$

# $$
\vec w = \vec w^{prev} - \frac {\alpha}{m}X^T(X \vec w - \vec y)
$$

### АБО

# $$
\vec h (X) = X\vec w
$$

# $$
\vec w = (X^T X)^{-1}X^T \vec y
$$

In [81]:
 def vec_v(X, vec_y):
        return np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), vec_y )

In [82]:
vec_v(x, y)

array([3.72448352e+02, 3.68974672e+05, 1.37031315e+06])

##### 6. Порівняйте отримані результати.

Результати аналітичного методу:

In [83]:
vec_v(x, y)

array([3.72448352e+02, 3.68974672e+05, 1.37031315e+06])

Результати SKLEARN:

In [84]:
reg.coef_

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

Висновки:

In [85]:
vec_v(x, y) < reg.coef_

array([ True,  True,  True])

In [86]:
# Коефіціенти по аналітичному способу трохи гірші.